### ISSUE TITLE
Run multiple cases in a toml file

### ISSUE THREAD

**Issue by epage** [assert-rs/trycmd#25]
`*.trycmd` files support this but not `*.toml`.  This discrepancy can push someone to `*.trycmd` files when they might be best served by the extra control of `*.toml` files.

Open Issues
- How do we handle expected stdout / stderr?
  - We currently read these from the file system which makes them global to the `*.toml` file.
  - If we add support for inline stdout, stderr, keep in mind
    - `binary` support
    - `TRYCMD=overwrite` support, see #23  (we are already using a format-preserving TOML library)

**Comment by pwinckles** [comment]
Couldn't you model it something like this, combing a few of the test cases in this project as an example:

```toml
bin.name = "bin-fixture"

[basic]

[sandbox]
fs.sandbox = true

[sandbox.env.add]
write = "file.txt = Goodbye\nWorld"
cat = "file.txt"

[stderr-to-stdout]
stderr-to-stdout = true

[stderr-to-stdout.env.add]
stdout = """
Hello
World!
"""
stderr = """
Goodnight
Moon!
"""
```

I haven't tried deserializing that, but I would expect that it'd look something like:

```rust
struct TomlFile {
    global: OneShot,
    cases: HashMap<String, OneShot>,
}
```

It might be a better idea to put the test cases in an array of tables though, `[[cases]]`.

So, if there are no cases are defined the current behavior is used. If cases are defined, then the `OneShot` objects are resolved by defaulting their values to whatever is in the global context, applying any values set in the case, and using the case's name as the name of the case (that is to say, if the case `basic` is in the file `tests.toml`, then it will look for `basic.in`,  `basic.out`, etc).
