### ISSUE TITLE
Option to not to normalize backslash

### ISSUE THREAD

**Issue by MiSawa** [assert-rs/trycmd#91]
I noticed that this fails due to "backslash to slash normalization".
```toml
bin.name = "bin-fixture"
stdout = '\'
[env.add]
stdout = '\'
```
It is probably useful for things that outputs paths, but is cumbersome for other things, e.g. a tool that outputs JSON, as test has to be `stdout = '"/"escaped/""'` for example instead of `stdout = '"\"escaped\""'`, and there's no way to check if the output was actually correctly escaped with `\`.
I know that there's a bin mode, but I still want line separators normalized. It'd be great to have a way to turn off the path separator normalization feature.

**Comment by epage** [comment]
The main question with this is deciding how to expose it.

**Comment by MiSawa** [comment]
It'd be great if it is exposed via `TestCases` for global default configuration like
```rust
let t = trycmd::TestCases::new()
t.output_normalize_path(false); // default: true (for compatibility)
t.output_normalize_line_separator(true); // default: true
```
and maybe per-test override via toml configuration
```toml
output_normalize_path = false
output_normalize_line_separator = true
```
though I guess it'll be a bit cumbersome to handle conflict with `binary = true/false`...
